### ISSUE TITLE
Problem loading example image

### ISSUE THREAD

**Issue by DanHickstein** [DanHickstein/pyBASEX#1]
Chunlong reports the following error when running the example: 

Python:>>> recon,speeds = BASEX.center_and_transform(raw_data,center,median_size=2,gaussian_blur=0,post_median=0,verbose=True)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "BASEX.py", line 139, in center_and_transform
    image = center_image(data,center=center)
  File "BASEX.py", line 159, in center_image
    H,W = np.shape(data)
ValueError: too many values to unpack

This seems to indicate that the image is not being loaded correctly. Maybe it is being loaded as a color image?

**Comment by DanHickstein** [comment]
The shape of the image was (1388,1038,4), so it looks like plt.imread was loading it in rbga color. I think that I solved this by loading the raw file instead. We'll see if it works for people.
